trigger:
- trunk
- dev
variables:
- name: versionStamp
  value: '[Build: $(Build.BuildNumber). Commit: $(Build.SourceVersion)]'
pool:
  vmImage: "ubuntu-latest"
steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: replacetokens@3
  inputs:
    rootDirectory: 'sass'
    targetFiles: 'style.scss'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build:dev'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/trunk'))
- task: DeleteFiles@1
  inputs:
    SourceFolder:
    Contents: |
      node_modules
      package*
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './'
    ArtifactName: 'bc-douglas-fir'
    publishLocation: 'Container'
